[project]
name = "cloud-cli"
version = "0.1.0"
description = "Cloud CLI tools for AWS and GCP"
readme = "README.md"
authors = [
    {name = "Dmitri Babaev", email = "dmitri.babaev@gmail.com"},
]
requires-python = ">=3.8"
dependencies = [
    "boto>=2.4",
    "google-cloud-storage>=1.18",
    "requests",
]

[dependency-groups]
dev = [
    "pylint",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.pylint.messages_control]
disable = [
    "C0111",  # missing-docstring
    "C0103",  # invalid-name
]

[tool.pylint.format]
max-line-length = 120 

[project.scripts]
ec2_ansible = "cloudcli:ec2_ansible"
ec2_ssh_config_sync = "cloudcli:ec2_ssh_config_sync"
ec2cmd = "cloudcli:ec2cmd"
gcs_cache = "cloudcli:gcs_cache"
http_cache = "cloudcli:http_cache"
s3cache = "cloudcli:s3cache"
